### ISSUE TITLE
Failed to send payload to https://api.delight.datamechanics.co/collector/bulk: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by damianopezzotti** [datamechanics/delight#4]
I'm trying to use delight in a java application that uses Spark as embedded library.
The application creates a new session and start to elaborate data inside application's jvm.

When I start the application, in the logs I can see these errors:

Failed to send payload to https://api.delight.datamechanics.co/collector/bulk: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Regards
Damiano

**Comment by jrj-d** [comment]
Hey Damiano, thanks for your feedback!

Can you share more about your environment? This type of TLS errors are usually caused by old versions of Java or custom setups.

Here are a few information that could be relevant:
* Java version
* Operating system and its version
* Has the Java `cacerts` truststore been modified?

**Comment by damianopezzotti** [comment]
Hi,
using Java Version 1.8.0_191 it works successfully

Thanks
